# Generated by Django 3.1.5 on 2021-01-12 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
