# Generated by Django 3.1.5 on 2021-01-20 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_delete_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='unm',
        ),
    ]
