# Generated by Django 3.1.5 on 2021-01-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_remove_signup_unm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email',
            new_name='email1',
        ),
    ]
