# Generated by Django 3.1.5 on 2021-02-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
