# Generated by Django 3.1.5 on 2021-02-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20210208_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_nm', models.CharField(max_length=50)),
            ],
        ),
    ]
